### ISSUE TITLE
How to use the repository for custom dataset.

### ISSUE THREAD

**Issue by kr-sundaram** [cdli-gh/Sumerian-NER#1]
Hey, I would like to use this repository for my dataset. My aim is to build translation model for En to De and De to En.

I am using Europarl En-De dataset and apart from this dataset, i have huge amount of monolingual DE dataset which also needs to be used for building a NMT model and i guess you guys are also trying to do same thing but for En-Sum dataset.

Can you please help me understanding how to use your repo for building model for POS, NER and NMT?

**Comment by himanshudce** [comment]
Hi, 
You can use different models available in POS and NER Repos. You can provide the dataset of your own, see the argument need to pass for using the model.
To use condition random field you need to use your own feature.py file as it is language-specific.
But as you have a large dataset you should go for the FLAIR language model. You can even integrate it with BERT and all other available embeddings. You can check FLAIR Repo for that, also for further references follow (https://github.com/flairNLP/flair).
Using different machine translation techniques you can use (https://github.com/cdli-gh/Unsupervised-NMT-for-Sumerian-English)
Soon I will update the documentation for further references.
